/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-11-24 23:07:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.parametros.conecion.*;

public final class menu1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.parametros.conecion");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Bootstrap demo</title>\r\n");
      out.write("<link href=\"bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("	");

	//http://localhost:8989/WebHome/index1.jsp?
	//http://localhost:9980/modelodb/m/FirstSteps?valormodulo=admision
	
	String vport = "1111";
	String vurl = "http://localhost:"+vport+"/modelodb/";
	String vurl1 = "http://localhost:"+vport+"/WebHome/index1.jsp";
	String vurl2 = "http://localhost:"+vport+"/WebHome/";

//	vurl = dc.LeerPropiedades("urlhome");
//	vurl1 = dc.LeerPropiedades("urldbhome");
	
	String vmod = "m/FirstSteps?valormodulo=";
	vmod = "?valormodulo=";
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	String vsitio = vurl + vmod;
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	String vmod1 = "nomina";
	vsitio = vurl + vmod + vmod1;
	
      out.write("\r\n");
      out.write("	<center>	\r\n");
      out.write("	<img src=\"logos.bmp\" height=\"100px\" widht=\"100px\" >\r\n");
      out.write("	</center>\r\n");
      out.write("	<br>	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\"></a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    	<h3>Beneficiarios</h3>\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Companias de Seguros\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"http://localhost:1111/modelodb/m/Aseguradoras?init=true\" target=\"principal\">Aseguradoras ( Seguros )</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"http://localhost:1111/modelodb/m/EmpresasConAseguradoras?init=true\" target=\"principal\">Empresas con Seguros</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("	<h3>Admision</h3>\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Admision\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"http://localhost:1111/modelodb/m/Admision?init=true\" target=\"principal\">Admisiones</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("	<h3>Usuarios</h3>\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Ver Usuario\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Cerrar Sesion</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h1>Benficiarios & Pacientes</h1>\r\n");
      out.write("\r\n");
      out.write("	<h3>Companias de Seguros</h3>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/Aseguradoras?init=true\" target=\"principal\">Aseguradoras ( Seguros )</a></li>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/EmpresasConAseguradoras?init=true\" target=\"principal\">Empresas con Seguros</a></li>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/Polizas?init=true\" target=\"principal\">Polizas</a></li>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/BeneficiariosConPolizas?init=true\" target=\"principal\">Beneficiarios</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("	<h3>Empresas</h3>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/EmpresasSinAseguradoras?init=true\" target=\"principal\">Empresas Sin Aseguradoras</a></li>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/Contratos?init=true\" target=\"principal\">Contratos</a></li>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/BeneficiariosConContratos?init=true\" target=\"principal\">Beneficiarios</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("	<h3>Habituales</h3>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/ContratosHabituales?init=true\" target=\"principal\">Contratos Habituales</a></li>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/BeneficiariosHabituales?init=true\" target=\"principal\">Beneficiarios</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("	<h3>Empresas Clinica Esperanza</h3>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/EmpresasDeClinicaEsperanza?init=true\" target=\"principal\">Empresa Clinica Esperanza</a></li>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/ContratosClinica?init=true\" target=\"principal\">Contratos de la Clinica</a></li>\r\n");
      out.write("		<li><a href=\"http://localhost:1111/modelodb/m/BeneficiariosDeLaClinica?init=true\" target=\"principal\">Beneficiarios</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("</hr>\r\n");
      out.write("</hr>\r\n");
      out.write("\r\n");
      out.write("<h3>Admision</h3>\r\n");
      out.write("<ul>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/Admision?init=true\" target=\"principal\">Admisiones</a></li>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/VerAdmisionesCerradas?init=true\" target=\"principal\">Ver Admisiones Cerradas</a></li>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/Paciente?init=true\" target=\"principal\">Ver Pacientes</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<h3>Inventario</h3>\r\n");
      out.write("<ul>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/VerInventarioCargado?init=true\" target=\"principal\">Ver Inventario Cargado</a></li>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/TipoDeInventario?init=true\" target=\"principal\">Tipos de Inventario</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<h3>Administrativo</h3>\r\n");
      out.write("<ul>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/FacturaAdministracion?init=true\" target=\"principal\">Factura de Administracion</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<h3>Pedidos Internos</h3>\r\n");
      out.write("<ul>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/PedidosInternos?init=true\" target=\"principal\">Pedidos Internos</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<h3>Farmacia</h3>\r\n");
      out.write("<ul>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/FacturaFarmacia?init=true\" target=\"principal\">Factura De Farmacia</a></li>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/FacturaVentaAlPublico?init=true\" target=\"principal\">Factura De Venta Al Publico</a></li>\r\n");
      out.write("	</hr>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/Proveedores?init=true\" target=\"principal\">Proveedores</a></li>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/OrdenDeCompra?init=true\" target=\"principal\">Orden De Compra</a></li>\r\n");
      out.write("	</hr>\r\n");
      out.write("	<li><a href=\"http://localhost:1111/modelodb/m/EstatusDeDocumentos?init=true\" target=\"principal\">Estatus</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</hr>\r\n");
      out.write("</hr>\r\n");
      out.write("</hr>\r\n");
      out.write("</hr>\r\n");
      out.write("</hr>\r\n");
      out.write("</hr>\r\n");
      out.write("</hr>\r\n");
      out.write("</hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<h3>*Tablas*</h3>\r\n");
      out.write("	<ul>\r\n");
      out.write("		");
 	vmod1 = "clinica"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">De La Clinica</a></li>\r\n");
      out.write("		");
 	vmod1 = "atablas"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">De Admisión</a></li>\r\n");
      out.write("		");
 	vmod1 = "ptablas"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">De Pacientes</a></li>\r\n");
      out.write("		");
 	vmod1 = "utablas"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">Ubicacion</a></li>\r\n");
      out.write("		");
 	vmod1 = "ftablas"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">Profesion</a></li>\r\n");
      out.write("		");
 	vmod1 = "itablas"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">De Inventario</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("	<h3>Nomina</h3>\r\n");
      out.write("	<ul>\r\n");
      out.write("		");
 	vmod1 = "nomina"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">Nomina</a></li>\r\n");
      out.write("		");
 	vmod1 = "notablas"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">Tablas</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("	<h3>Reportes</h3>\r\n");
      out.write("	<ul>\r\n");
      out.write("		");
 	vmod1 = "reportes"; vsitio = vurl + vmod + vmod1; 	
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print(vsitio);
      out.write("\" target=\"principal\">De Saldos Pendientes</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
